---
abstract: 'Authentication Store with Crowd REST service'
author:
  - 'Keerati Thiwanruk <keerati.th@gmail.com>'
build_requires:
  Catalyst: 0
  Catalyst::Controller: 0
  FindBin: 0
  IO::Socket::SSL: 0
  Test::Fake::HTTPD: 0
  Test::More: 0
  Test::TCP: 0
  Test::WWW::Mechanize::Catalyst: 0
  namespace::autoclean: 0
  strict: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Authentication-Store-Crowd
requires:
  Catalyst::Authentication::User: 0
  HTTP::Request: 0
  JSON: 0
  LWP::UserAgent: 0
  Moose: 0
  warnings: 0
version: 0.04
